# Generated by Django 3.2.8 on 2021-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='pimage')),
                ('img2', models.ImageField(upload_to='pimage')),
                ('img3', models.ImageField(upload_to='pimage')),
                ('p_name', models.CharField(max_length=500)),
                ('p_type', models.CharField(max_length=500)),
                ('p_url', models.CharField(max_length=200)),
                ('p_disc', models.TextField()),
            ],
        ),
    ]
