# Generated by Django 3.2.8 on 2021-11-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_lang',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
