# Generated by Django 3.2.8 on 2021-11-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_project_p_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.CharField(max_length=500),
        ),
    ]
